# 管理端口的开放配置
management:
  endpoints:
    web:
      exposure:
        include: env,encrypt
  endpoint:
    env:
      enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # 注意，不能用default-zone version:Greenwich.SR1
      defaultZone: http://localhost:9010/eureka/
