spring:
  application:
    name: eurekaSever
server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/